FROM node:16.13.0 as build

WORKDIR /usr/local/app

RUN npm install -g @angular/cli

EXPOSE 4200

RUN ["/bin/bash"]

# COPY ./ /usr/local/app/


# RUN npm install

# RUN npm run build


# FROM nginx:latest

# COPY --from=build /usr/local/app/dist/sample-angular-app /usr/share/nginx/html

# EXPOSE 80