version: '3'
services:
    angular-frontend:
        image: "node_frontend"
        container_name: 'node_frontend'
        stdin_open: true
        tty: true
        ports:
            - "4200:4200"
        volumes:
            - ./:/usr/local/app
        build:
          context: .
          dockerfile: Dockerfile.dev
        
           