version: '3'
services:
    go-backend:
        image: 'go_backend'
        container_name: 'go_backend'
        build:
            context: .
            dockerfile: Dockerfile
            args:
                key: $SARA_KEY
                secret: $SARA_SECRET
        
           