version: '3'
services:
  redis-server:
    image: 'redis'
    stdin_open: true
    tty: true

  rest-backend:
    image: 'rest_backend'
    container_name: 'rest_backend'
    depends_on:
      - redis-server
    stdin_open: true
    tty: true
    ports:
      - "9090:9090"
    environment:
      - GOOGLE_API_ID=${GOOGLE_API_ID}
      - GOOGLE_API_SECRET=${GOOGLE_API_SECRET}
    build:
        context: .
        dockerfile: ./Dockerfile.rest
        
  grpc-backend:
    image: 'grpc_backend'
    container_name: 'grpc_backend'
    stdin_open: true
    tty: true
    ports:
        - "9091:9091"
    build:
        context: .
        dockerfile: ./Dockerfile.grpc
