
#Golang Image
FROM golang:latest

WORKDIR /app

COPY ./rest /app

EXPOSE 9090

CMD ["go","test", "./...", "-v", "-cover"]



# RUN go get -u github.com/golang/protobuf/protoc-gen-go
# RUN go get -u google.golang.org/grpc