// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: proto/sara.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PictureLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNumber int32 `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
}

func (x *PictureLinksRequest) Reset() {
	*x = PictureLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sara_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureLinksRequest) ProtoMessage() {}

func (x *PictureLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sara_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureLinksRequest.ProtoReflect.Descriptor instead.
func (*PictureLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_sara_proto_rawDescGZIP(), []int{0}
}

func (x *PictureLinksRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type PictureLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *PictureLinksResponse) Reset() {
	*x = PictureLinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sara_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureLinksResponse) ProtoMessage() {}

func (x *PictureLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sara_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureLinksResponse.ProtoReflect.Descriptor instead.
func (*PictureLinksResponse) Descriptor() ([]byte, []int) {
	return file_proto_sara_proto_rawDescGZIP(), []int{1}
}

func (x *PictureLinksResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_proto_sara_proto protoreflect.FileDescriptor

var file_proto_sara_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x13, 0x70, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x2a, 0x0a, 0x14, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x32, 0x62,
	0x0a, 0x13, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_sara_proto_rawDescOnce sync.Once
	file_proto_sara_proto_rawDescData = file_proto_sara_proto_rawDesc
)

func file_proto_sara_proto_rawDescGZIP() []byte {
	file_proto_sara_proto_rawDescOnce.Do(func() {
		file_proto_sara_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sara_proto_rawDescData)
	})
	return file_proto_sara_proto_rawDescData
}

var file_proto_sara_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sara_proto_goTypes = []interface{}{
	(*PictureLinksRequest)(nil),  // 0: server.pictureLinksRequest
	(*PictureLinksResponse)(nil), // 1: server.pictureLinksResponse
}
var file_proto_sara_proto_depIdxs = []int32{
	0, // 0: server.pictureLinksService.pictureLinks:input_type -> server.pictureLinksRequest
	1, // 1: server.pictureLinksService.pictureLinks:output_type -> server.pictureLinksResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sara_proto_init() }
func file_proto_sara_proto_init() {
	if File_proto_sara_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sara_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sara_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureLinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sara_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sara_proto_goTypes,
		DependencyIndexes: file_proto_sara_proto_depIdxs,
		MessageInfos:      file_proto_sara_proto_msgTypes,
	}.Build()
	File_proto_sara_proto = out.File
	file_proto_sara_proto_rawDesc = nil
	file_proto_sara_proto_goTypes = nil
	file_proto_sara_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PictureLinksServiceClient is the client API for PictureLinksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PictureLinksServiceClient interface {
	PictureLinks(ctx context.Context, in *PictureLinksRequest, opts ...grpc.CallOption) (*PictureLinksResponse, error)
}

type pictureLinksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPictureLinksServiceClient(cc grpc.ClientConnInterface) PictureLinksServiceClient {
	return &pictureLinksServiceClient{cc}
}

func (c *pictureLinksServiceClient) PictureLinks(ctx context.Context, in *PictureLinksRequest, opts ...grpc.CallOption) (*PictureLinksResponse, error) {
	out := new(PictureLinksResponse)
	err := c.cc.Invoke(ctx, "/server.pictureLinksService/pictureLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PictureLinksServiceServer is the server API for PictureLinksService service.
type PictureLinksServiceServer interface {
	PictureLinks(context.Context, *PictureLinksRequest) (*PictureLinksResponse, error)
}

// UnimplementedPictureLinksServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPictureLinksServiceServer struct {
}

func (*UnimplementedPictureLinksServiceServer) PictureLinks(context.Context, *PictureLinksRequest) (*PictureLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PictureLinks not implemented")
}

func RegisterPictureLinksServiceServer(s *grpc.Server, srv PictureLinksServiceServer) {
	s.RegisterService(&_PictureLinksService_serviceDesc, srv)
}

func _PictureLinksService_PictureLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PictureLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureLinksServiceServer).PictureLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.pictureLinksService/PictureLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureLinksServiceServer).PictureLinks(ctx, req.(*PictureLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PictureLinksService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.pictureLinksService",
	HandlerType: (*PictureLinksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "pictureLinks",
			Handler:    _PictureLinksService_PictureLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sara.proto",
}
